# Generated by Django 3.0.4 on 2020-04-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peinture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('peintures', models.ManyToManyField(to='peinture.Peinture')),
            ],
        ),
        migrations.AlterField(
            model_name='style',
            name='peintures',
            field=models.ManyToManyField(to='peinture.SubStyle'),
        ),
    ]
