# Generated by Django 3.0.4 on 2020-04-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peinture', '0002_auto_20200403_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='peintures',
            field=models.ManyToManyField(blank=True, to='peinture.Peinture'),
        ),
    ]
