# Generated by Django 3.0.4 on 2020-04-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peinture', '0005_auto_20200403_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='substyle',
        ),
        migrations.AddField(
            model_name='peinture',
            name='substyle',
            field=models.ManyToManyField(to='peinture.Style'),
        ),
        migrations.DeleteModel(
            name='SubStyle',
        ),
    ]
