# Generated by Django 3.0.4 on 2020-04-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peinture', '0006_auto_20200403_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peinture',
            name='substyle',
        ),
        migrations.AddField(
            model_name='peinture',
            name='categorie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='peinture',
            name='style',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Style',
        ),
    ]
