# Generated by Django 3.0.4 on 2020-04-04 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peinture', '0009_auto_20200404_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='peintures',
        ),
        migrations.AddField(
            model_name='categorie',
            name='name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='peinture',
            name='categorie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='peinture.Categorie'),
        ),
    ]
