# Generated by Django 3.0.4 on 2020-04-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peinture', '0010_auto_20200404_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='peinture',
            name='desc',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
