# Generated by Django 3.0.4 on 2020-04-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peinture', '0012_remove_peinture_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='peinture',
            name='style',
            field=models.CharField(choices=[('Acryliques', 'Acryliques'), ('Encres', 'Encres'), ('Huiles', 'Huiles'), ('Aquarelles', 'Aquarelles')], default='Acryliques', max_length=50),
        ),
    ]
