# Generated by Django 3.0.4 on 2020-04-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expomodel',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
