# Generated by Django 3.0.4 on 2020-04-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0002_expomodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expomodel',
            name='date',
            field=models.DateField(auto_now=True, db_index=True),
        ),
    ]
