# Generated by Django 3.0.4 on 2020-04-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0003_auto_20200403_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expomodel',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
