# Generated by Django 3.0.4 on 2020-04-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expo', '0004_auto_20200403_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='expomodel',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
