# Generated by Django 3.0.4 on 2020-04-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=51)),
                ('email', models.CharField(max_length=51)),
                ('comment', models.CharField(max_length=600)),
            ],
        ),
    ]
