# Generated by Django 3.0.4 on 2020-04-02 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 4, 2, 13, 36, 57, 705180)),
        ),
    ]
