# Generated by Django 3.0.4 on 2020-04-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0003_auto_20200402_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaire',
            name='email',
            field=models.CharField(blank=True, max_length=51),
        ),
    ]
