# Generated by Django 3.0.4 on 2020-04-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0004_auto_20200402_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
